# Generated by Django 4.2.11 on 2026-07-30 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='straightneedle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='straightneedle',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spindle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spindle',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='interchangeabletip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interchangeabletip',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='interchangeablecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interchangeablecord',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='fixedcircular',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedcircular',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='doublepointedneedle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doublepointedneedle',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='crochethook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crochethook',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddField(
            model_name='cableneedle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cableneedle',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool_tracker.storagelocation'),
        ),
        migrations.AddConstraint(
            model_name='straightneedle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('total_length_in'), models.F('diameter_mm'), models.F('us_size'), name='unique_straight'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='spindle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('spindle_type'), models.F('whorl_position'), models.F('weight_oz'), models.F('whorl_diameter_mm'), name='unique_spindle'),
        ),
        migrations.AddConstraint(
            model_name='interchangeabletip',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('tip_length_in'), models.F('diameter_mm'), models.F('us_size'), models.F('interchangeable_system'), name='unique_interchangeable_tip'),
        ),
        migrations.AddConstraint(
            model_name='interchangeablecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('cord_length_in'), models.F('cord_color'), models.F('interchangeable_system'), name='unique_interchangeable_cord'),
        ),
        migrations.AddConstraint(
            model_name='fixedcircular',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('tip_length_in'), models.F('diameter_mm'), models.F('us_size'), models.F('total_length_in'), name='unique_fixed_circular'),
        ),
        migrations.AddConstraint(
            model_name='doublepointedneedle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('total_length_in'), models.F('diameter_mm'), models.F('us_size'), name='unique_dpn'),
        ),
        migrations.AddConstraint(
            model_name='crochethook',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('diameter_mm'), models.F('us_size'), name='unique_crochet_hook'),
        ),
        migrations.AddConstraint(
            model_name='cableneedle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('brand'), django.db.models.functions.text.Lower('model'), models.F('tip_length_in'), models.F('diameter_mm'), models.F('us_size'), name='unique_cable_needle'),
        ),
    ]
